apiVersion: v1
kind: ConfigMap
metadata:
  name: policy-files
  namespace: demo
data:
  policy1.yaml: |
    apiVersion: json.kyverno.io/v1alpha1
    kind: ValidatingPolicy
    metadata:
      name: test-policy
    spec:
      rules:
        - name: deny-external-calls-testapp-1
          match:
            any:
            - request:
                http:
                    host: 'testapp-1.demo.svc.cluster.local:8080'
          assert:
            all:
            - message: "The GET method is restricted to the /book path."
              check:
                request:
                    http:
                        method: 'GET'
                        path: '/book'
  policy2.yaml: |
    apiVersion: json.kyverno.io/v1alpha1
    kind: ValidatingPolicy
    metadata:
      name: test-policy
    spec:
      rules:
        - name: deny-external-calls-testapp-2
          match:
            any:
            - request:
                http:
                    host: 'testapp-2.demo.svc.cluster.local:8080'
          assert:
            all:
            - message: "The GET method is restricted to the /movies path."
              check:
                request:
                    http:
                        method: 'GET'
                        path: '/movie'                