apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-1
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp-1
  template:
    metadata:
      labels:
        app: testapp-1
    spec:
      containers:
      - name: testapp-1
        image: sanskardevops/test-application:0.0.1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: testapp-1
  namespace: demo
spec:
  type: NodePort
  selector:
    app: testapp-1
  ports:
  - port: 8080
    targetPort: 8080
