{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
metadata:
  name: {{ template "kyverno-authz-server.name" . }}
  namespace: {{ template "kyverno.lib.namespace" . }}
  labels:
    {{- include "kyverno-authz-server.labels" . | nindent 4 }}
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
{{- end -}}
