version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: kyverno-envoy-plugin
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    binary: kyverno-envoy-plugin
    flags:
      - -trimpath
    ldflags:
      - -s -w

kos:
  - build: kyverno-envoy-plugin
    repository: ghcr.io/kyverno/kyverno-envoy-plugin
    tags:
      - '{{ .Tag }}'
      - '{{ if not .Prerelease }}latest{{ end }}' 
    bare: true
    preserve_import_paths: false
    sbom: none
    platforms:
      - all
    labels:
      org.opencontainers.image.source: https://github.com/kyverno/kyverno-envoy-plugin
      org.opencontainers.image.description: Kyverno policies based authorization plugin for Envoy ❤️

signs:
  - cmd: cosign
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - --output-certificate=${certificate}
      - --output-signature=${signature}
      - ${artifact}
      - --yes
    artifacts: all
    output: true

docker_signs:
  - cmd: cosign
    artifacts: all
    output: true
    args:
      - sign
      - ${artifact}
      - --yes

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: checksums.txt

source:
  enabled: true

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

snapshot:
  version_template: '{{ incpatch .Version }}-next'

release:
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
