apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "sidecar-injector.name" . }}
  labels:
    {{- include "sidecar-injector.labels" . | nindent 4 }}
  {{- if (or .Values.certificates.certManager .Values.webhook.annotations) }}
  annotations:
    {{- with .Values.webhook.annotations }}
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
    {{- if .Values.certificates.certManager }}
    cert-manager.io/inject-ca-from: {{ printf "%s/%s" (include "kyverno.lib.namespace" .) (include "sidecar-injector.name" .) }}
    {{- end }}
  {{- end }}
webhooks:
  - name: {{ printf "%s.%s.svc" (include "sidecar-injector.name" .) (include "kyverno.lib.namespace" .) }}
    clientConfig:
      service:
        name: {{ template "sidecar-injector.name" . }}
        namespace: {{ template "kyverno.lib.namespace" . }}
        path: /mutate
      {{- if .Values.certificates.static }}
      caBundle: {{ index .Values.certificates.static.crt | b64enc }}
      {{- end }}
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    sideEffects: None
    admissionReviewVersions: [ v1 ]
    rules:
      - apiGroups: [ '' ]
        apiVersions: [ v1 ]
        resources: [ pods ]
        operations: [ CREATE ]
        scope: '*'
    {{- with .Values.webhook.objectSelector }}
    objectSelector:
      {{- tpl (toYaml .) $ | nindent 6 }}
    {{- end }}
    {{- with .Values.webhook.namespaceSelector }}
    namespaceSelector:
      {{- tpl (toYaml .) $ | nindent 6 }}
    {{- end }}
