{{- if .Values.sidecarInjector.enabled -}}
{{- if .Values.sidecarInjector.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kyverno.sidecar-injector.role.name" . }}
  labels:
    {{- include "kyverno.sidecar-injector.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
      - list
{{- end -}}
{{- end -}}
