{{- if .Values.sidecarInjector.enabled -}}
{{- if .Values.sidecarInjector.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kyverno.sidecar-injector.service-account.name" . }}
  namespace: {{ template "kyverno.namespace" . }}
  labels:
    {{- include "kyverno.sidecar-injector.labels" . | nindent 4 }}
{{- end -}}
{{- end -}}
