
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: kyverno-envoy-sidecar
  labels:
    app.kubernetes.io/name: sidecar-injector
    app.kubernetes.io/instance: sidecar-injector
webhooks:
  - name: kyverno-envoy-sidecar.kyverno-envoy-sidecar-injector.svc
    clientConfig:
      service:
        name: kyverno-envoy-sidecar
        namespace: kyverno-envoy-sidecar-injector
        path: "/mutate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZsakNDQTM2Z0F3SUJBZ0lVVFNGS2k0NDlzYWNmUXF4UTVnWFhBanU5SjA0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd096RTVNRGNHQTFVRUF3d3dhM1ZpWlhKdVpYUmxjeTF6YVdSbFkyRnlMV2x1YW1WamRHOXlMbk5wWkdWagpZWEl0YVc1cVpXTjBiM0l1YzNaak1CNFhEVEkwTURReE5qRXhNVFl3TlZvWERUSTFNRFF4TmpFeE1UWXdOVm93Ck96RTVNRGNHQTFVRUF3d3dhM1ZpWlhKdVpYUmxjeTF6YVdSbFkyRnlMV2x1YW1WamRHOXlMbk5wWkdWallYSXQKYVc1cVpXTjBiM0l1YzNaak1JSUNJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBdFNSeApXMWpGbWJrTW1GOWZzK05yREY3NUFBQzY2aDg3UGRnOGpKaDEwWjRGRDlVallDVUhqL1RuVVg4d3V3cVVoWTVmCjUyTU1sV1AxMi9FWkNQc2lKL3VGMjA1aWRsa3k1UWkvNzBtVzZUUEpMTkFhcHpxa2pSZDBGbklXUllKOXJ1cS8KZDdEOHYwaHJtaUJZUHhaR0VEVEhWWDBGMWFwRTBncEZtRE1vU200ZjRYZEdTazNuc3N3YWptSTBJYk1aaURpRwpKcmVQOXFSMDIwU0VxUEpNQng0ZUdQSVFEVmtiMlgwanV3ZXljbFhHUWduWWFhRFhZd0czWUNqcmRXWUtYcEF5CkJmNUpLNlZaNkNVWVluWmpSd1U5c2xSS0xGRDhiNlpiUXIzQmR0UmpRRDBheG5aZ0wwa0xKamsvSVBsQk55eEwKclZwRG83VWpCY1FrVVgvZ1k3UjBreFRIcG9GUVZzOXlHY3M2Wi9NeE4wNUIrSGlEYzVGcjBhUEU0Vm9XR3E5TwptaEFSYmZuNDRqcm92b0tVTThXOGR4NjFyeFR3cklLejdKVW1BOGdKRFFIL2hVTjFJMlEyQ0ZXNXpHYUNHdVBBCjBuSHJzMzF2Q0N4dTBybTM2N3Bnd3RIbDhLWEE1aW9hN1Zia1NpZkZ3MDVCaitrOHFPSkNDSFd4ZG5IVVNhSUoKU2RWaW5LaXBUOS9INmdNRHg4dUxNRnhTM2txVm9Oa1hxMlVTOTFjN3B2Rk9Qdi9HQzBrTWNmSkN3SVdoK3JJdAp2VDhjc1BOaXVWWGdEOXg2QjhKSUErSi9XOUV1L2VuWU8xdzhoVnc5cXVhUVdEMi9MYkdNd01LQWlyUUlBSkRaCjk4Y1pFaVFUcnpTTGdxTDhzQWR2eTRsNG5MUUdQN2lEWUVmZGxLa0NBd0VBQWFPQmtUQ0JqakFkQmdOVkhRNEUKRmdRVUN3NUdQOVlVMC9xZ3pEejFmcDh0alhFdXhBb3dId1lEVlIwakJCZ3dGb0FVQ3c1R1A5WVUwL3FnekR6MQpmcDh0alhFdXhBb3dEd1lEVlIwVEFRSC9CQVV3QXdFQi96QTdCZ05WSFJFRU5EQXlnakJyZFdKbGNtNWxkR1Z6CkxYTnBaR1ZqWVhJdGFXNXFaV04wYjNJdWMybGtaV05oY2kxcGJtcGxZM1J2Y2k1emRtTXdEUVlKS29aSWh2Y04KQVFFTEJRQURnZ0lCQUowTDFmc2tGVHRWenBXZWlBaXNxWVFzTmxMWUhkczNyNGVkRzhiS0w3bWZtYm5pZllmOQpjblphYWxVaWRrazU3VFpVMFYrdlc5M2RONGZ3cXZ3a1IzL240V2dpbEZRR3RmekI2WURoZnRBNlRlZUI3Y3lRCmZnSmVCakRPYndIMzNHVDlmWDlVZFNaSTJ1dVJRRGZ5RW1mWEd3aHVSajJpdS9XQ3MxT2cvb01WUy9XM1VCb2EKSis4YXVQWUViSTRrcmtBUkJvOEJ2SGxKeGxjdWRnTjg1bWFMMWc4OWU5U0s1WVM2Ymswa3lKa1J1ZFNNZ2ZvbgpoRkJHcjR1emJrSmpWYmZzVUxiWGZEOTB3ZXpIekQ4NG5OTVhWTExrSU9YMm9SSFZaKzI4V0I5TzVKeWxOUWllCjk0UWJVWTFnMkpPYzZodUNYS0h1KzdqQlRRTzdHYWZTbFBHcTBreUl4eDh6bXd5T1h2M3M2OVZJQkNqbVcwSnQKTlZqYTNDVzViS1FmbU90ODRoOFJuVmJtVmN6b3RZcWVJOGNBVlJCL0V1NzM2UkZzeGNSL3JFeEdyZ3BIZG9IeApQNUF4bTBJTlVBQnVrZjlJbStLSXFOOUxKRzF5M3hocGxWNzAySmxKWElFcDFOeGoyMGlWaDZlZ3FsNksvTE5pCjc4VkdxdFBwM1FqVUtIMkRicExsRnluTGdoNm8zM1NHWjRlNWtXbXB4djdyUncrblJhZEo0ekRoa0hkWjZ1ZjIKMFoyTG9ZVmpMdExRTEljclRxcENVODRSUDg5WjN4cFF1N3lHQlptVVc2OURIUFVmcm9LZ25UUTZyODJYY21IUQpKTkV2TS93VXlpdUhsY1Erb2pCZ2ZSd2MzRjNkblZ6VHZ4N1drKzVaMkdFbVk4NEp6SE9TQmIvdAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1"]
    rules:
      - apiGroups:
          - ""
        resources:
          - pods
        apiVersions:
          - "v1"
        operations:
          - CREATE
        scope: '*'  
    objectSelector:
      matchExpressions:
        - key: kyverno-envoy-sidecar/injection
          operator: In
          values:
          - enabled
                  
---