//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationServer) DeepCopyInto(out *AuthorizationServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationServer.
func (in *AuthorizationServer) DeepCopy() *AuthorizationServer {
	if in == nil {
		return nil
	}
	out := new(AuthorizationServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthorizationServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationServerList) DeepCopyInto(out *AuthorizationServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AuthorizationServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationServerList.
func (in *AuthorizationServerList) DeepCopy() *AuthorizationServerList {
	if in == nil {
		return nil
	}
	out := new(AuthorizationServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthorizationServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationServerPolicySource) DeepCopyInto(out *AuthorizationServerPolicySource) {
	*out = *in
	in.KubernetesPolicySource.DeepCopyInto(&out.KubernetesPolicySource)
	out.ExternalPolicySource = in.ExternalPolicySource
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationServerPolicySource.
func (in *AuthorizationServerPolicySource) DeepCopy() *AuthorizationServerPolicySource {
	if in == nil {
		return nil
	}
	out := new(AuthorizationServerPolicySource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationServerSpec) DeepCopyInto(out *AuthorizationServerSpec) {
	*out = *in
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]AuthorizationServerPolicySource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationServerSpec.
func (in *AuthorizationServerSpec) DeepCopy() *AuthorizationServerSpec {
	if in == nil {
		return nil
	}
	out := new(AuthorizationServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalPolicySource) DeepCopyInto(out *ExternalPolicySource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalPolicySource.
func (in *ExternalPolicySource) DeepCopy() *ExternalPolicySource {
	if in == nil {
		return nil
	}
	out := new(ExternalPolicySource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesPolicySource) DeepCopyInto(out *KubernetesPolicySource) {
	*out = *in
	in.PolicyRef.DeepCopyInto(&out.PolicyRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesPolicySource.
func (in *KubernetesPolicySource) DeepCopy() *KubernetesPolicySource {
	if in == nil {
		return nil
	}
	out := new(KubernetesPolicySource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyObjectReference) DeepCopyInto(out *PolicyObjectReference) {
	*out = *in
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(Group)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(Kind)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(ObjectName)
		**out = **in
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyObjectReference.
func (in *PolicyObjectReference) DeepCopy() *PolicyObjectReference {
	if in == nil {
		return nil
	}
	out := new(PolicyObjectReference)
	in.DeepCopyInto(out)
	return out
}
