# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Dev docs

permissions: {}

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Build site
        run: |
          set -e
          make codegen-mkdocs
      - name: Deploy site
        run: |
          set -e
          git fetch origin gh-pages --depth=1
          git config user.name ci-bot
          git config user.email ci-bot@example.com
          mike deploy -F ./website/mkdocs.yaml --push --update-aliases main dev
